core/urls.py
from django.urls import path
from . import views

app_name="core"

urlpatterns = [
    path('list/stadium/',views.ListStadium.as_view(), name="list_st"),
    path('add/stadium/',views.AddStadium.as_view(), name="add_st"),
    path('update/stadium/<int:pk>/', views.UpdateStadium.as_view(), name= "update_st"),
    path('delete/stadium/<int:pk>/', views.DeleteStadium.as_view(), name= "delete_st"),
    
    path('list/city/',views.ListCity.as_view(), name="list_city"),
    path('add/city/',views.AddCity.as_view(), name="add_city"),
    path('update/city/<int:pk>/', views.UpdateCity.as_view(), name= "update_city"),
    path('delete/city/<int:pk>/', views.DeleteCity.as_view(), name= "delete_city"),

    path('list/team/',views.ListTeam.as_view(), name="list_tm"),
    path('add/team/',views.AddTeam.as_view(), name="add_tm"),
    path('update/team/<int:pk>/', views.UpdateTeam.as_view(), name= "update_tm"),
    path('delete/team/<int:pk>/', views.DeleteTeam.as_view(), name= "delete_tm"),
]

home/urls.py
from django.urls import path, include
from home import views

app_name="home"

urlpatterns = [
   path('', views.Index.as_view(),name='index') 
]

nfl/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('core.urls')),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User

# Models NFL

class Stadium(models.Model):
    stadium_name=models.CharField(max_length=64)
    status=models.BooleanField(default=True)
    timestamp=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.stadium_name
    

class City(models.Model):
    stadium=models.ForeignKey(Stadium, on_delete=models.CASCADE)
    city_name=models.CharField(max_length=64)
    status=models.BooleanField(default=True)
    timestamp=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.city_name

class Team(models.Model):
    city=models.ForeignKey(City, on_delete=models.CASCADE)
    stadium=models.ForeignKey(Stadium, on_delete=models.CASCADE)
    team_name=models.CharField(max_length=64)
    description=models.CharField(max_length=285)
    status=models.BooleanField(default=True)
    timestamp=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.team_name

home/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from .models import *

# Form : Stadium

class AddStadiumForm(forms.ModelForm):
    class Meta:
        model = Stadium
        fields = "__all__"
        widgets = {
            "name_stadium": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Enter the name of the stadium"}),
            "status": forms.CheckboxInput(attrs={"type":"checkbox"}),
                         }



class UpdateStadiumForm(forms.ModelForm):
    class Meta:
        model = Stadium
        fields = "__all__"
        widgets = {
            "name_stadium": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Enter the name of the stadium"}),
            "status": forms.CheckboxInput(attrs={"type":"checkbox"}),
                         }



# Form : City

class AddCityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = "__all__"
        widgets = {
            "stadium": forms.Select(attrs={"class":"form-select form-control"}),
            "city_name": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Enter the name of the city"}),
            "status": forms.CheckboxInput(attrs={"type":"checkbox"}),
            }

class UpdateCityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = "__all__"
        widgets = {
            "stadium": forms.Select(attrs={"class":"form-select form-control"}),
            "city_name": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Enter the name of the city"}),
            "status": forms.CheckboxInput(attrs={"type":"checkbox"}),
            }
        


# Form : Team 

class AddTeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = "__all__"
        widgets = {
            "stadium": forms.Select(attrs={"class":"form-select form-control"}),
            "city": forms.Select(attrs={"class":"form-select form-control"}),
            "team_name": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Enter the name of the team"}),
            "description": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Enter the description"}),
            "status": forms.CheckboxInput(attrs={"type":"checkbox"}),
            }
        
class UpdateTeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = "__all__"
        widgets = {
            "stadium": forms.Select(attrs={"class":"form-select form-control"}),
            "city": forms.Select(attrs={"class":"form-select form-control"}),
            "team_name": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Enter the name of the team"}),
            "description": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Enter the description"}),
            "status": forms.CheckboxInput(attrs={"type":"checkbox"}),
            }

core/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .models import *
from .forms import *


# create : views   for    stadium

class ListStadium(generic.View):
    template_name = "core/stadium/list_st.html"
    context = {}

    def get(self, request, *args, **kwargs):
        stadium = Stadium.objects.filter(status=True)
        self.context = {
            "stadiums": stadium
        }
        return render(request, self.template_name,self.context)


class AddStadium(generic.CreateView):
    template_name = "core/stadium/add_st.html"
    model = Stadium
    form_class = AddStadiumForm
    success_url = reverse_lazy("core:list_st")


class UpdateStadium(generic.UpdateView):
    template_name = "core/stadium/update_st.html"
    model = Stadium
    form_class = UpdateStadiumForm
    success_url = reverse_lazy('core:list_st')

class DeleteStadium(generic.DeleteView):
    template_name = "core/stadium/delete_st.html"
    model = Stadium
    success_url = reverse_lazy("core:list_st")




# create : views   for    City

class ListCity(generic.View):
    template_name = "core/city/list_city.html"
    context = {}

    def get(self, request, *args, **kwargs):
        city = City.objects.filter(status=True)
        self.context = {
            "citys": city
        }
        return render(request, self.template_name,self.context)

class AddCity(generic.CreateView):
    template_name = "core/city/add_city.html"
    model = City
    form_class = AddCityForm
    success_url = reverse_lazy("core:list_city")

class UpdateCity(generic.UpdateView):
    template_name = "core/city/update_city.html"
    model = City
    form_class = UpdateCityForm
    success_url = reverse_lazy("core:list_city")

class DeleteCity(generic.DeleteView):
    template_name = "core/city/delete_city.html"
    model = City
    success_url = reverse_lazy("core:list_city")


# create : views   for    Team

class ListTeam(generic.View):
    template_name = "core/team/list_tm.html"
    context = {}

    def get(self, request, *args, **kwargs):
        team =  Team.objects.filter(status=True)
        self.context = {
            "teams": team
        }
        return render(request, self.template_name,self.context)
    
class AddTeam(generic.CreateView):
    template_name = "core/team/add_tm.html"
    model = Team
    form_class = AddTeamForm
    success_url = reverse_lazy("core:list_tm")

class UpdateTeam(generic.UpdateView):
    template_name = "core/team/update_tm.html"
    model = Team
    form_class = UpdateTeamForm
    success_url = reverse_lazy("core/team/list_tm")

class DeleteTeam(generic.DeleteView):
    template_name = "core/team/delete_tm.html"
    model = Team
    success_url = reverse_lazy("core:list_tm")

home/views.py
from django.shortcuts import render
from django.views import generic

# Create your views here.

class Index(generic.View):
    template_name = "home/index.html"
    context={}
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)

templates/base/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title%}{% endblock title%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<style>
  body{
    font-size: 20px;
  }
</style>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg" style="background-color: #97d4ff;">
    <div class="container-md">
      <a class="navbar-brand" href="{% url 'home:index' %}">NFL Management</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:list_st' %}">Stadium</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:list_city' %}">City</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:list_tm' %}">Team</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  {% block content %}




  
  {% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

templates/core/city/add_city.html
{% extends "base/base.html" %}

{% block title %}
ADD CITY
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Enter City</button>
        <a href="{% url 'core:list_city' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

templates/core/city/delete_city.html
{% extends "base/base.html" %}

{% block title %}
DELETE CITY
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        Are you sure you want to delete: {{ object.city_name}}?
        <button type="submit" class="btn btn-outline-danger">Delete City</button>
        <a href="{% url 'core:list_city' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

templates/core/city/list_city.html
{% extends 'base/base.html' %}

{% block title %} 
LIST CITYS
{% endblock title %}




{% block content %}

<style>

    body{
        font-size: 20px;
    }
    .sucess{
        margin: 100px;
    }
    h1{
        text-align: center;
    }
</style>

    <div class="sucess">
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <a href="{% url 'core:add_city' %}" class="btn btn-success">Add City</a>
        </div>
    </div>
    <h1>List of citys in the NFL</h1>
    <br>
    <hr>
    <br>
    <div class="table-responsive py-2">
      <table class="table table-striped">
        <thead>
            <th></th>
            <th>#</th>
            <th></th>
            <th>NAME</th>
            <th></th>
            <th>STADIUM</th>
            <th colspan="2">OPTIONS</th>

        </thead>
        <tbody>
            {% for c in citys %}
                <tr>
                    <td></td>
                    <td>{{ c.id }}</td>
                    <td></td>
                    <td>{{ c.city_name }}</td>
                    <td></td>
                    <td>{{ c.stadium }}</td>
                    <td><a href="{% url 'core:update_city' c.id %}" class="btn btn-warning">Update</a></td>
                    <td><a href="{% url 'core:delete_city' c.id %}" class="btn btn-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
       </table>
{% endblock content %}

templates/core/city/update_city.html
{% extends "base/base.html" %}

{% block title %}
UPDATE CITY
{% endblock title %}

{% block content %}

<div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
    <div class="card">
        <div class="card-body">
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary">Update City</button>
        <a href="{% url 'core:list_city' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
</div>
</div>
</div>
{% endblock content %}

templates/core/stadium/add_st.html
{% extends "base/base.html" %}

{% block title %}
ADD STADIUM
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Add estadio</button>
        <a href="{% url 'core:list_st' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

templates/core/stadium/delete_st.html
{% extends "base/base.html" %}

{% block title %}
DELETE STADIUM
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        Are you sure you want to delete:{{ object.stadium_name }}?
        <button type="submit" class="btn btn-outline-danger">Delete Stadium</button>
        <a href="{% url 'core:list_st' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

templates/core/stadium/list_st.html
{% extends 'base/base.html' %}

{% block title %} 
LIST STADIUM
{% endblock title %}




{% block content %}

<style>

    body{
        font-size: 20px;
    }
    .sucess{
        margin: 100px;
    }
    h1{
        text-align: center;
    }
</style>

    <div class="sucess">
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <a href="{% url 'core:add_st' %}" class="btn btn-success">Add Stadium</a>
        </div>
    </div>
    <h1>List of stadiums in the NFL</h1>
    <br>
    <hr>
    <br>
    <div class="table-responsive py-2">
      <table class="table table-striped">
        <thead>
            <th></th>
            <th>#</th>
            <th></th>
            <th>NAME</th>
            <th></th>
            <th colspan="2">OPTIONS</th>

        </thead>
        <tbody>
            {% for s in stadiums %}
                <tr>
                    <td></td>
                    <td>{{ s.id }}</td>
                    <td></td>
                    <td>{{ s.stadium_name }}</td>
                    <td></td>
                    <td><a href="{% url 'core:update_st' s.id %}" class="btn btn-warning">Update</a></td>
                    <td><a href="{% url 'core:delete_st' s.id %}" class="btn btn-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
       </table>
{% endblock content %}

templates/core/stadium/update_st.html
{% extends "base/base.html" %}

{% block title %}
UPDATE STADIUM
{% endblock title %}

{% block content %}

<div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
<div class="card">
    <div class="card-body">
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary">Update Stadium</button>
        <a href="{% url 'core:list_st' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
</div>
</div>
</div>
{% endblock content %}

templates/core/team/add_tm.html
{% extends "base/base.html" %}

{% block title %}
ADD TEAM
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Add Team</button>
        <a href="{% url 'core:list_tm' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

templates/core/team/delete_tm.html
{% extends "base/base.html" %}

{% block title %}
DELETE TEAM
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        Are you sure you want to delete:{{ object.team_name }}?
        <button type="submit" class="btn btn-outline-danger">Delete Team</button>
        <a href="{% url 'core:list_tm' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

templates/core/team/list_tm.html
{% extends 'base/base.html' %}

{% block title %}
LIST TEAMS
{% endblock title %}

{% block content %}

<style>

    body{
        font-size: 20px;
    }
    .sucess{
        margin: 100px;
    }
    h1{
        text-align: center;
    }
</style>

<div class="sucess">
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a href="{% url 'core:add_tm' %}" class="btn btn-success">Add Team</a>
    </div>
   
</div>
<h1>List of Teams in the NFL</h1>
<br>
<hr>
<br>
<div class="table-responsive py-2">
  <table class="table table-striped">
    <thead>
        <th></th>
        <th>#</th>
        <th></th>
        <th>NAME</th>
        <th></th>
        <th>CITY</th>
        <th></th>
        <th>STADIUM</th>
        <th></th>
        <th>DESCRIPTION</th>
        <th></th>
        <th>STATUS</th>
        <th></th>
        <th>OPTIONS</th>

    </thead>
    <tbody>
        {% for t in teams %}
            <tr>
                <td></td>
                <td>{{ t.id }}</td>
                <td></td>
                <td>{{ t.team_name }}</td>
                <td></td>
                <td>{{ t.city }}</td>
                <td></td>
                <td>{{ t.stadium }}</td>
                <td></td>
                <td>{{ t.description }}</td>
                <td></td>
                <td>{{ t.status }}</td>
                <td></td>
                <td><a href="{% url 'core:update_tm' t.id %}" class="btn btn-warning">Update</a></td>
                <td><a href="{% url 'core:delete_tm' t.id %}" class="btn btn-danger">Delete</a></td>
            </tr>
        {% endfor %}
    </tbody>
   </table>
{% endblock content %}

templates/core/team/update_tm.html
{% extends "base/base.html" %}

{% block title %}
UPDATE TEAM
{% endblock title %}

{% block content %}
<div class="card">
    <div class="card-body">
     <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary">Update Team</button>
        <a href="{% url 'core:list_tm' %}" class="btn btn-outline-warning">Cancel</a>
     </form>
    </div>
</div>
{% endblock content %}

templates/home/index.html
{% extends "base/base.html" %}
{% block title %}National Football League{% endblock title %}
<link rel="shortcut icon" href="nfl.jpeg">
{%block content%}

<style>
    body{
        background-image: url("home/nfl.jpeg");
    }
</style>
<div class="table-responsive py-2">
<table class="table table-striped table-hover">
    <thead>
        <th>Teams that play stadium:</th>
        <th></th>
        <th>Teams that belong to the city:</th>
        <th></th>

    </thead>
    <tbody>
        {% for t in teams %}
            <tr>
                <td>{{ t.stadium }}</td>
                <td></td>
                <td>{{ t.city }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
</div>



{%endblock content%}